Source:
- changed-files:
  - any-glob-to-any-file: 'src/**/*'
  - all-globs-to-all-files: '!src/docs/*'

Pytest:
- changed-files:
  - any-glob-to-any-file: "**/test_*.py"
  - any-glob-to-any-file: "tests/*"
  - any-glob-to-any-file: "tests/**/*"

CICD:
- changed-files:
  - any-glob-to-any-file: ".github/**"
  - any-glob-to-any-file: ".github/workflows/**"

Code Style:
- changed-files:
  - any-glob-to-any-file: ".pre-commit-config.yaml"
  - any-glob-to-any-file: "pyproject.toml"

Dependencies:
- changed-files:
  - any-glob-to-any-file: "requirements.txt"

Documentation:
- changed-files:
  - any-glob-to-any-file: "**/*.md"
  - any-glob-to-any-file: "docs/*"

feature:
 - head-branch: ["^feature", "feature", "feat/*"]

release:
 - base-branch: "master"
