version: '3.8'

services:
  base:
    image: repo-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
    restart: always

  postgresql:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: always
