name: Pull Request Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Labeler
        id: labeler
        uses: actions/labeler@v5
        with:
          sync-labels: true
          configuration-path: .github/labeler.yml
