name: Update Workflow Container and Create PR

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new branch
        run: git checkout -b update-container-$(date +%Y%m%d%H%M%S)

      - name: Update container in workflow files
        run: |
          shopt -s globstar nullglob
          for file in .github/workflows/*.y*ml; do
            awk '/runs-on: ubuntu-latest/ { print; print "    container: catthehacker/ubuntu:act-latest"; next }1' "$file" > tmpfile && mv tmpfile "$file"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update container in workflow files"

      - name: Push changes
        run: git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update container in workflow files"
          body: "This PR updates the container in all workflow files."
          branch: "update-container-$(date +%Y%m%d%H%M%S)"
          base: "gitea"
