name: Build Package

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build_package:
    name: Build Package by Rye
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-20.04

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.0.0

      # - name: Setup SSH Key
      #   uses: shimataro/ssh-key-action@v2.7.0
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: unnecessary
      #     config: |
      #       Host *
      #         StrictHostKeyChecking no
      #         UserKnownHostsFile=/dev/null
      #     if_key_exists: replace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Setup Rye
        run: |
          make rye-install
          ~/.rye/shims/rye pin 3.10
          ~/.rye/shims/rye sync
          ~/.rye/shims/rye --version

      - name: Build Package
        run: |
          ~/.rye/shims/rye build --clean
