name: Validate Release and Change Log

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate-release:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag from the changelog
        uses: denisa/clq-action@v1
        id: clq-extract
        with:
          mode: release

      - name: Validate the tag has not yet been used
        uses: denisa/semantic-tag-helper@v1
        with:
          mode: test
          tag: ${{ steps.clq-extract.outputs.tag }}
