# This action has been disabled since it is not frequently used.
# Just leave it for the sake of the example.

name: Release Drafter

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  update_release_draft:
    name: Update Release Draft
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@v6
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: false
          disable-autolabeler: true

  # build_package:
  #   name: Build Executable File
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: windows-latest

  #   steps:
  #     - name: Disable SSL Verify
  #       run: git config --global http.sslVerify false

  #     - name: Checkout
  #       uses: actions/checkout@v4.1.2
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Python
  #       uses: actions/setup-python@v5.1.0
  #       with:
  #         python-version: '3.10'
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Packaging to Executable file
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install pyinstaller
  #         pyinstaller -F main.py --onefile -n ${{ github.event.repository.name }}

  #     - name: Move and Rename
  #       shell: pwsh
  #       run: |
  #         Move-Item -Path ./configs -Destination ./dist/
  #         Move-Item -Path ./src -Destination ./dist/
  #         Move-Item -Path ./data -Destination ./dist/
  #         Move-Item -Path ./binaries -Destination ./dist/

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4.3.3
  #       with:
  #         path: ./dist/*
  #         name: ${{ github.event.repository.name }}
  #         if-no-files-found: ignore
  #         retention-days: 90
  #         compression-level: 6
  #         overwrite: true

  #     # - name: Download Artifact
  #     #   uses: actions/download-artifact@v4
  #     #   with:
  #     #     name: ${{ github.event.repository.name }}

  #     # - name: List files
  #     #   shell: pwsh
  #     #   run: |
  #     #     Get-ChildItem -Path .

  # upload_artifacts:
  #   name: Upload Release Assets
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   needs: build_package
  #   runs-on: ubuntu-latest
  #   # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v4
  #       if: startsWith(github.ref, 'refs/tags/v')
  #       with:
  #         name: ${{ github.event.repository.name }}

  #     - name: Check Files
  #       run: |
  #         cd ..
  #         zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
  #         ls -al
  #         cp -R ${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}/

  #     - name: Upload Release Assets
  #       uses: softprops/action-gh-release@v2
  #       if: startsWith(github.ref, 'refs/tags/v')
  #       # continue-on-error: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         name: ${{ steps.drafter.outputs.name }}
  #         tag_name: ${{ steps.drafter.outputs.tag_name }}
  #         files: |
  #           ${{ github.event.repository.name }}.exe
  #           ${{ github.event.repository.name }}.zip
